backstab:
    items:
        359:
            chance: 1.0
            critchance: 0.5
            critmultiplier: 3
            multiplier: 2
            onsneak: true
            critonsneak: true
            maxangle: 90.0
    attackermsg: "Backstab!"
    victimmsg: "You got stabbed in the back!"
    critmsg: "CRITICAL!"
poison:
    items:
        294:
            poison:
                type: POISON
                chance: 1.0
                duration: 5
                strength: 0
                onsneak: true
                maxangle: 90
hook:
    pullitem: 287
    hookitem: 262
    blocktime: 5
    maxdistance: 100
    distancetoinitial: 10
    itemsperblock: 0.01
    errormsg: "You can't hook there!"
    initialmsg: "You are to far away from your initial location!"
    distancemsg: "Your hook is to far away!"