name: WayOfShadows
main: com.syd.wayofshadows.WayOfShadows
dev-url: http://dev.bukkit.org/server-mods/WayOfShadows
version: 0.2
description: Poison, backstab and hook!
permissions:
  shadow.backstab:
    description: Backstab your enemies!
    default: false
  shadow.poison:
    description: Poison your enemyie!
    default: false
  shadow.hook:
    description: Hook yourself over walls
    default: false