name: WayOfShadows
main: de.craftlancer.wayofshadows.WayOfShadows
dev-url: http://dev.bukkit.org/server-mods/WayOfShadows
version: 0.5
description: Effect, BackStab, GrapplingHook, AirAssassionation and PickPocket skills
softdepend: [SkillLevels]
permissions:
  shadow.<skillname>:    
    description: Allows you to use the skill with all valid items
    default: false
  shadow.<skillname>.item.<id>:    
    description: Allows you to use the skill with items with id <id>.
    default: false
  shadow.<skillname>.name.<name>:    
    description: Allows you to use the skill with items with name <name>.
    default: false
  shadow.<skillname>.lore.<lore>:    
    description: Allows you to use the skill with items which lore contains the String <lore>.
    default: false