configVersion: 2
backstab:
  type: backstab
  lore: []
  items: 
    - IRON_SWORD
    - STONE_SWORD
    - DIAMOND_SWORD
    - GOLD_SWORD
    - WOOD_SWORD
    - SHEARS
    - BOW
  names: 
    - BackStabItem
  chance: 1
  critChance: 0.5
  multiplier: 2.0
  critMultiplier: 3.0
  maxAngle: 90.0
  onSneak: true
  critOnSneak: true
  attackerMsg: Backstab!
  victimMsg: You got stabbed in the back!
  critMsg: CRITICAL!
poison:
  type: effect
  lore: []
  items:
  - GOLD_HOE
  itemNames: []
  effectType: POISON
  chance: 1
  maxAngle: 90.0
  duration: 5
  strength: 0
  onSneak: true
hook:
  lore: []
  items:
  - ARROW
  itemNames: []
  type: grapplinghook
  pullLore: []
  pullItems:
  - STRING
  pullItemNames: []
  distanceMsg: Your hook is to far away!
  initialMsg: You are to far away from your initial location!
  errorMsg: You can't hook there!
  blockTime: 100.0
  maxDistance: 100.0
  distanceToInitial: 10.0
  itemsPerBlock: 0.01
pickpocket:
  type: pickpocket
  cooldown: 120
  cooldownMsg: Pickpocket is for %time% seconds on cooldown!
  maxAngle: 90
  chance: 1
  maxValue: 100
  maxDistance: 8
  onSneak: true
  abortOnDamage: true
  valueCatalogue: default
  maxValueMsg: You already stole enough!
  cantStealMsg: You can't steal that!
  stealFailedMsg: You failed in stealing this item.
  attemptStealMsg: Is there something moving in your pockets?
airassassin:
  type: airassassination
  chance: 1
  minHeight: 5
  maxHeight: 4
  damagePerHeight: 24
  negateFallOnSuccess : true
lockpick:
  type: lockpick
  cooldown: 10
  cooldownMsg: Lockpick is for %time% seconds on cooldown.
  successMsg: You successfully picked to lock!
  failMsg: You failed at picking the lock!
  closeCooldownMsg: You can't close this for another %time% seconds!
  items:
    - GOLD_INGOT
  chance: 0.25*y
  loseItemOnFail: true
  loseItemOnSuccess: true
  damageOnFail: 5
  closeCooldown: 300
  pickable:
    WOODEN_DOOR: 1
    TRAP_DOOR: 1
    FENCE_GATE: 1
    LEVER: 1
    
    
  