name: WayOfShadows
main: de.craftlancer.wayofshadows.WayOfShadows
dev-url: http://dev.bukkit.org/server-mods/WayOfShadows
version: ${project.version}
description: Effect, BackStab, GrapplingHook, AirAssassionation and PickPocket skills
softdepend: [SkillLevels]
permissions:
  shadow.reload:
    description: Allows to use the /wayofshadows command, which reloads the plugin's config and skills
    default: op
commands:
  wayofshadows:
    description: Reload the plugin
    usage: Reload the plugin